### PR TITLE
This pull request is to merge feature-branch to development branch of the members only article posting app. 

### PR DESCRIPTION
**Pull request by henatan99**
This pull request is to merge feature-branch to development branch of the members only article posting app. The app lets anyone to see the posted articles but limits the post creation privilege to signed in users only. It has a user signup form, sign in form and post create form. It uses devise gem to manages the user model authentication functionalities.

### CODE REVIEW

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @henatan99 and @elisha2kyakpo1  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] As a signed-in user you can create new post ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/signed_in_can_post_requirement.png) from theodinproject) => To create a post is not accepting, fix that before submitting another code review request
- [x] As a signed-in user you can see post's author ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/signed_in_can_see_author_requirement.png) from Odin)
- [x] As a guest you can see only post's text ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/guest_can_see_only_posts_requirement.png) from Odin)
- [x] Change the `user_id` from the post's migration from text to integer :point_right:  Do that using another migration, don't edit the pre-existing migration
- [x] The PostController should use `before_action` to restrict access to the `:new` and `:create` methods ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/before_action_requirement.png) from Odin)

# [Optional changes] :yellow_circle: 
- [ ] It would be very nice if you style well the pages, currently they have an incomplete stylings
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by elisha2kyakpo1** [comment]
Hello @descholar-ceo, thanks for the review. I wanted to remind you that we have used the before_action in the post controller, not in the application controller just in case you did not see it.

**Comment by descholar-ceo** [comment]
Hello @elisha2kyakpo1, thank you for reaching out for clarification, I saw it but it's not filtering the actions you were required to filter. Look into that carefully!

**Comment by henatan99** [comment]
> # Status: Changes Required  
> ## Hello @henatan99 and @elisha2kyakpo1   
>  This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
> 
> ####  However we need to make few changes to mark this project approved. See the requested change below   
> ### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding
> # [Required Changes] 
> * [x]  As a signed-in user you can create new post ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/signed_in_can_post_requirement.png) from theodinproject) => To create a post is not accepting, fix that before submitting another code review request
> * [x]  As a signed-in user you can see post's author ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/signed_in_can_see_author_requirement.png) from Odin)
> * [x]  As a guest you can see only post's text ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/guest_can_see_only_posts_requirement.png) from Odin)
> * [x]  Change the `user_id` from the post's migration from text to integer point_right  Do that using another migration, don't edit the pre-existing migration
> * [x]  The PostController should use `before_action` to restrict access to the `:new` and `:create` methods ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/before_action_requirement.png) from Odin)
> 
> # [Optional changes] 
> * [ ]  It would be very nice if you style well the pages, currently they have an incomplete stylings
> 
> _If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._
> 
> [GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)
> 
> _Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

Hi @descholar-ceo 
We have made the requested changes but changes 2 and 3 are something we have already done. The app doesn't show the posts users when not logged in but it shows the email of the posts users when logged in

**Review by arslanbisharat — APPROVED** [review]
# Approved :smile: 

Hello Developer :wave:

I just reviewed your project and I am very happy to inform you that your project is approved.
Congratulations on achieving this milestone in your career. :clap:


_I am looking forward to seeing your next project._

Stay safe and give me a smile 😇

### Happy Coding
------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Comment by henatan99** [comment]
Hi @descholar-ceo 
We have made the requested changes but I think changes 2 and 3 are something we have already done. The app doesn't show the posts users when not logged in but it shows the email of the posts users when logged in

**Comment by descholar-ceo** [comment]
@henatan99 that's very okay, keep up the good work!

**Pull request merged**
